import type { CultureTemplate } from '@/entities/agro/culture-template/types';

const sourceTags = {
  beds: 'Horta 2026 - PLANEJAMENTO DOS CANTEIROS.csv',
  prices: 'DUNAMIS AGRO REAL - NOVA TABELA DE PREÇOS.csv',
  planning: 'Dunamis Agro - Planejamento.csv'
} as const;

const pricedLeafy = {
  seedCostCents: 19,
  inputCostCents: 3,
  maintenanceCostCents: 1,
  utilitiesCostCents: 13,
  laborCostCents: 87,
  totalEstimatedCostCents: 123
};

const zeroCosts = {
  seedCostCents: 0,
  inputCostCents: 0,
  maintenanceCostCents: 0,
  utilitiesCostCents: 0,
  laborCostCents: 0,
  totalEstimatedCostCents: 0
};

const createTemplate = (template: CultureTemplate): CultureTemplate => template;

export const cultureTemplates: CultureTemplate[] = [
  createTemplate({
    id: 'tpl-alface-americana',
    name: 'Alface',
    variant: 'Americana',
    category: 'Folhosa',
    cycleDays: 40,
    purchaseTypeDefault: 'caixa',
    unitsPerPurchasePack: 200,
    productionUnitDefault: 'muda',
    salesUnitDefault: 'unidade',
    unitsPerSalesBox: 12,
    spacingBetweenPlantsCm: 30,
    spacingBetweenRowsCm: 30,
    bedLengthDefaultM: 50,
    bedWidthDefaultM: 0.9,
    plantsPerBed: 498,
    weeklyProductionEstimate: 249,
    bedsWithoutBreak: 4,
    ...pricedLeafy,
    notes: 'Base da tabela de preços real; planejamento indica 498 plantas por canteiro.',
    sourceTags: [sourceTags.beds, sourceTags.prices, sourceTags.planning],
    recommendedMarkupPct: 35,
    defaultLossRate: 8,
    environmentType: 'canteiro',
    groupTag: 'alfaces',
    active: true
  }),
  createTemplate({
    id: 'tpl-alface-crespa',
    name: 'Alface',
    variant: 'Crespa',
    category: 'Folhosa',
    cycleDays: 40,
    purchaseTypeDefault: 'caixa',
    unitsPerPurchasePack: 200,
    productionUnitDefault: 'muda',
    salesUnitDefault: 'unidade',
    unitsPerSalesBox: 12,
    spacingBetweenPlantsCm: 30,
    spacingBetweenRowsCm: 30,
    bedLengthDefaultM: 50,
    bedWidthDefaultM: 0.9,
    plantsPerBed: 498,
    weeklyProductionEstimate: 249,
    bedsWithoutBreak: 4,
    ...pricedLeafy,
    notes: 'Usa o mesmo baseline de custo unitário da tabela real.',
    sourceTags: [sourceTags.beds, sourceTags.prices, sourceTags.planning],
    recommendedMarkupPct: 35,
    defaultLossRate: 8,
    environmentType: 'canteiro',
    groupTag: 'alfaces',
    active: true
  }),
  createTemplate({
    id: 'tpl-alface-roxa',
    name: 'Alface',
    variant: 'Roxa',
    category: 'Folhosa',
    cycleDays: 40,
    purchaseTypeDefault: 'caixa',
    unitsPerPurchasePack: 200,
    productionUnitDefault: 'muda',
    salesUnitDefault: 'unidade',
    unitsPerSalesBox: 12,
    spacingBetweenPlantsCm: 30,
    spacingBetweenRowsCm: 30,
    bedLengthDefaultM: 50,
    bedWidthDefaultM: 0.9,
    plantsPerBed: 498,
    weeklyProductionEstimate: 249,
    bedsWithoutBreak: 4,
    ...pricedLeafy,
    notes: 'Mantém o mesmo desenho de canteiro da família de alfaces.',
    sourceTags: [sourceTags.beds, sourceTags.prices, sourceTags.planning],
    recommendedMarkupPct: 35,
    defaultLossRate: 8,
    environmentType: 'canteiro',
    groupTag: 'alfaces',
    active: true
  }),
  createTemplate({
    id: 'tpl-alface-lisa',
    name: 'Alface',
    variant: 'Lisa',
    category: 'Folhosa',
    cycleDays: 40,
    purchaseTypeDefault: 'caixa',
    unitsPerPurchasePack: 200,
    productionUnitDefault: 'muda',
    salesUnitDefault: 'unidade',
    unitsPerSalesBox: 12,
    spacingBetweenPlantsCm: 30,
    spacingBetweenRowsCm: 30,
    bedLengthDefaultM: 50,
    bedWidthDefaultM: 0.9,
    plantsPerBed: 498,
    weeklyProductionEstimate: 249,
    bedsWithoutBreak: 4,
    ...pricedLeafy,
    notes: 'Custos reais encontrados na tabela de preços.',
    sourceTags: [sourceTags.beds, sourceTags.prices, sourceTags.planning],
    recommendedMarkupPct: 35,
    defaultLossRate: 8,
    environmentType: 'canteiro',
    groupTag: 'alfaces',
    active: true
  }),
  createTemplate({
    id: 'tpl-rucula',
    name: 'Rúcula',
    variant: 'Cultivada',
    category: 'Folhosa',
    cycleDays: 30,
    purchaseTypeDefault: 'bandeja',
    unitsPerPurchasePack: 288,
    productionUnitDefault: 'muda',
    salesUnitDefault: 'maco',
    unitsPerSalesBox: 18,
    spacingBetweenPlantsCm: 20,
    spacingBetweenRowsCm: 20,
    bedLengthDefaultM: 50,
    bedWidthDefaultM: 1,
    plantsPerBed: 1250,
    weeklyProductionEstimate: 469,
    bedsWithoutBreak: 2,
    ...pricedLeafy,
    notes: 'Planejamento indica 1.250 plantas por canteiro e giro de 30 dias.',
    sourceTags: [sourceTags.beds, sourceTags.prices, sourceTags.planning],
    recommendedMarkupPct: 38,
    defaultLossRate: 10,
    environmentType: 'canteiro',
    groupTag: 'folhosas',
    active: true
  }),
  createTemplate({
    id: 'tpl-agriao',
    name: 'Agrião',
    variant: 'Folha',
    category: 'Folhosa',
    cycleDays: 65,
    purchaseTypeDefault: 'bandeja',
    unitsPerPurchasePack: 288,
    productionUnitDefault: 'muda',
    salesUnitDefault: 'maco',
    unitsPerSalesBox: 18,
    spacingBetweenPlantsCm: 20,
    spacingBetweenRowsCm: 20,
    bedLengthDefaultM: 50,
    bedWidthDefaultM: 1,
    plantsPerBed: 1250,
    weeklyProductionEstimate: 156,
    bedsWithoutBreak: 1.25,
    ...zeroCosts,
    notes: 'Sem custo direto na tabela de preços; baseline de planejamento mantido.',
    sourceTags: [sourceTags.beds, sourceTags.planning],
    recommendedMarkupPct: 40,
    defaultLossRate: 10,
    environmentType: 'canteiro',
    groupTag: 'folhosas',
    active: true
  }),
  createTemplate({
    id: 'tpl-folha-beterraba',
    name: 'Folha de Beterraba',
    variant: 'Folha',
    category: 'Folhosa',
    cycleDays: 45,
    purchaseTypeDefault: 'bandeja',
    unitsPerPurchasePack: 288,
    productionUnitDefault: 'muda',
    salesUnitDefault: 'maco',
    unitsPerSalesBox: 16,
    spacingBetweenPlantsCm: 20,
    spacingBetweenRowsCm: 20,
    bedLengthDefaultM: 50,
    bedWidthDefaultM: 1,
    plantsPerBed: 1250,
    weeklyProductionEstimate: 156,
    bedsWithoutBreak: 1,
    ...pricedLeafy,
    notes: 'Tem custo real na tabela de preços; manejo segue grupo de folhas.',
    sourceTags: [sourceTags.beds, sourceTags.prices, sourceTags.planning],
    recommendedMarkupPct: 38,
    defaultLossRate: 10,
    environmentType: 'canteiro',
    groupTag: 'folhosas',
    active: true
  }),
  createTemplate({
    id: 'tpl-beterraba',
    name: 'Beterraba',
    variant: 'Raiz',
    category: 'Raiz',
    cycleDays: 85,
    purchaseTypeDefault: 'saco',
    unitsPerPurchasePack: 1500,
    productionUnitDefault: 'unidade',
    salesUnitDefault: 'unidade',
    unitsPerSalesBox: 20,
    spacingBetweenPlantsCm: 30,
    spacingBetweenRowsCm: 10,
    bedLengthDefaultM: 50,
    bedWidthDefaultM: 0.9,
    plantsPerBed: 1500,
    weeklyProductionEstimate: 188,
    bedsWithoutBreak: 1.6,
    ...pricedLeafy,
    notes: 'Planejamento separa beterraba raiz de folha; custo real encontrado na tabela.',
    sourceTags: [sourceTags.beds, sourceTags.prices, sourceTags.planning],
    recommendedMarkupPct: 35,
    defaultLossRate: 12,
    environmentType: 'canteiro',
    groupTag: 'raizes',
    active: true
  }),
  createTemplate({
    id: 'tpl-couve-manteiga',
    name: 'Couve',
    variant: 'Manteiga',
    category: 'Brassica / crucífera',
    cycleDays: 30,
    purchaseTypeDefault: 'caixa',
    unitsPerPurchasePack: 200,
    productionUnitDefault: 'muda',
    salesUnitDefault: 'unidade',
    unitsPerSalesBox: 10,
    spacingBetweenPlantsCm: 50,
    spacingBetweenRowsCm: 50,
    bedLengthDefaultM: 50,
    bedWidthDefaultM: 1,
    plantsPerBed: 200,
    weeklyProductionEstimate: 50,
    bedsWithoutBreak: 1.5,
    ...zeroCosts,
    notes: 'Sai no planejamento como grupo de canteiros perenes de folha.',
    sourceTags: [sourceTags.beds, sourceTags.planning],
    recommendedMarkupPct: 38,
    defaultLossRate: 12,
    environmentType: 'canteiro',
    groupTag: 'brassicas',
    active: true
  }),
  createTemplate({
    id: 'tpl-couve-detox-kale',
    name: 'Couve Detox',
    variant: 'Kale',
    category: 'Brassica / crucífera',
    cycleDays: 35,
    purchaseTypeDefault: 'caixa',
    unitsPerPurchasePack: 200,
    productionUnitDefault: 'muda',
    salesUnitDefault: 'unidade',
    unitsPerSalesBox: 10,
    spacingBetweenPlantsCm: 50,
    spacingBetweenRowsCm: 50,
    bedLengthDefaultM: 50,
    bedWidthDefaultM: 1,
    plantsPerBed: 200,
    weeklyProductionEstimate: 25,
    bedsWithoutBreak: 0.75,
    ...zeroCosts,
    notes: 'Template criado a partir do planejamento de canteiros sem quebra.',
    sourceTags: [sourceTags.beds, sourceTags.planning],
    recommendedMarkupPct: 40,
    defaultLossRate: 12,
    environmentType: 'canteiro',
    groupTag: 'brassicas',
    active: true
  }),
  createTemplate({
    id: 'tpl-couve-flor',
    name: 'Couve-flor',
    variant: 'Branca',
    category: 'Brassica / crucífera',
    cycleDays: 45,
    purchaseTypeDefault: 'caixa',
    unitsPerPurchasePack: 200,
    productionUnitDefault: 'muda',
    salesUnitDefault: 'cabeca',
    unitsPerSalesBox: 8,
    spacingBetweenPlantsCm: 50,
    spacingBetweenRowsCm: 50,
    bedLengthDefaultM: 50,
    bedWidthDefaultM: 1,
    plantsPerBed: 200,
    weeklyProductionEstimate: 25,
    bedsWithoutBreak: 1,
    ...zeroCosts,
    notes: 'Sem preço-base encontrado; manter ajuste manual de custo ao usar.',
    sourceTags: [sourceTags.beds, sourceTags.planning],
    recommendedMarkupPct: 40,
    defaultLossRate: 12,
    environmentType: 'canteiro',
    groupTag: 'brassicas',
    active: true
  }),
  createTemplate({
    id: 'tpl-brocolis-japones',
    name: 'Brócolis',
    variant: 'Japonês',
    category: 'Brassica / crucífera',
    cycleDays: 65,
    purchaseTypeDefault: 'caixa',
    unitsPerPurchasePack: 200,
    productionUnitDefault: 'muda',
    salesUnitDefault: 'cabeca',
    unitsPerSalesBox: 8,
    spacingBetweenPlantsCm: 50,
    spacingBetweenRowsCm: 50,
    bedLengthDefaultM: 50,
    bedWidthDefaultM: 1,
    plantsPerBed: 200,
    weeklyProductionEstimate: 100,
    bedsWithoutBreak: 5,
    ...zeroCosts,
    notes: 'Planejamento aponta 5 canteiros sem quebra para manter oferta.',
    sourceTags: [sourceTags.beds, sourceTags.planning],
    recommendedMarkupPct: 40,
    defaultLossRate: 12,
    environmentType: 'canteiro',
    groupTag: 'brassicas',
    active: true
  }),
  createTemplate({
    id: 'tpl-acelga',
    name: 'Acelga',
    variant: 'Verde',
    category: 'Folhosa',
    cycleDays: 65,
    purchaseTypeDefault: 'caixa',
    unitsPerPurchasePack: 200,
    productionUnitDefault: 'muda',
    salesUnitDefault: 'cabeca',
    unitsPerSalesBox: 8,
    spacingBetweenPlantsCm: 50,
    spacingBetweenRowsCm: 50,
    bedLengthDefaultM: 50,
    bedWidthDefaultM: 1,
    plantsPerBed: 200,
    weeklyProductionEstimate: 25,
    bedsWithoutBreak: 1.25,
    ...zeroCosts,
    notes: 'Mantido como folhosa de ciclo longo conforme planejamento.',
    sourceTags: [sourceTags.beds, sourceTags.planning],
    recommendedMarkupPct: 40,
    defaultLossRate: 10,
    environmentType: 'canteiro',
    groupTag: 'folhosas',
    active: true
  }),
  createTemplate({
    id: 'tpl-rabanete',
    name: 'Rabanete',
    variant: 'Raiz',
    category: 'Raiz',
    cycleDays: 45,
    purchaseTypeDefault: 'saco',
    unitsPerPurchasePack: 1500,
    productionUnitDefault: 'unidade',
    salesUnitDefault: 'maco',
    unitsPerSalesBox: 20,
    spacingBetweenPlantsCm: 30,
    spacingBetweenRowsCm: 10,
    bedLengthDefaultM: 50,
    bedWidthDefaultM: 0.9,
    plantsPerBed: 1500,
    weeklyProductionEstimate: 750,
    bedsWithoutBreak: 4,
    ...pricedLeafy,
    notes: 'Template usa custo real da tabela e capacidade do planejamento.',
    sourceTags: [sourceTags.beds, sourceTags.prices, sourceTags.planning],
    recommendedMarkupPct: 35,
    defaultLossRate: 10,
    environmentType: 'canteiro',
    groupTag: 'raizes',
    active: true
  }),
  createTemplate({
    id: 'tpl-cenoura',
    name: 'Cenoura',
    variant: 'Raiz',
    category: 'Raiz',
    cycleDays: 55,
    purchaseTypeDefault: 'saco',
    unitsPerPurchasePack: 1500,
    productionUnitDefault: 'unidade',
    salesUnitDefault: 'maco',
    unitsPerSalesBox: 24,
    spacingBetweenPlantsCm: 30,
    spacingBetweenRowsCm: 10,
    bedLengthDefaultM: 50,
    bedWidthDefaultM: 0.9,
    plantsPerBed: 1500,
    weeklyProductionEstimate: 750,
    bedsWithoutBreak: 5,
    ...zeroCosts,
    notes: 'Sem custo direto no CSV de preços; usar como base de espaçamento e produção.',
    sourceTags: [sourceTags.beds, sourceTags.planning],
    recommendedMarkupPct: 35,
    defaultLossRate: 12,
    environmentType: 'canteiro',
    groupTag: 'raizes',
    active: true
  }),
  createTemplate({
    id: 'tpl-salsinha',
    name: 'Salsinha',
    variant: 'Lisa',
    category: 'Erva / tempero',
    cycleDays: 30,
    purchaseTypeDefault: 'bandeja',
    unitsPerPurchasePack: 288,
    productionUnitDefault: 'muda',
    salesUnitDefault: 'maco',
    unitsPerSalesBox: 20,
    spacingBetweenPlantsCm: 20,
    spacingBetweenRowsCm: 20,
    bedLengthDefaultM: 50,
    bedWidthDefaultM: 1,
    plantsPerBed: 1250,
    weeklyProductionEstimate: 63,
    bedsWithoutBreak: 0.25,
    ...pricedLeafy,
    notes: 'Custo unitário real encontrado na tabela de preços.',
    sourceTags: [sourceTags.beds, sourceTags.prices, sourceTags.planning],
    recommendedMarkupPct: 40,
    defaultLossRate: 10,
    environmentType: 'canteiro',
    groupTag: 'temperos',
    active: true
  }),
  createTemplate({
    id: 'tpl-cebolinha',
    name: 'Cebolinha',
    variant: 'Comum',
    category: 'Erva / tempero',
    cycleDays: 70,
    purchaseTypeDefault: 'bandeja',
    unitsPerPurchasePack: 288,
    productionUnitDefault: 'muda',
    salesUnitDefault: 'maco',
    unitsPerSalesBox: 20,
    spacingBetweenPlantsCm: 20,
    spacingBetweenRowsCm: 20,
    bedLengthDefaultM: 50,
    bedWidthDefaultM: 1,
    plantsPerBed: 1250,
    weeklyProductionEstimate: 63,
    bedsWithoutBreak: 0.6,
    ...pricedLeafy,
    notes: 'Baseline de custo real com giro mais longo no planejamento.',
    sourceTags: [sourceTags.beds, sourceTags.prices, sourceTags.planning],
    recommendedMarkupPct: 40,
    defaultLossRate: 10,
    environmentType: 'canteiro',
    groupTag: 'temperos',
    active: true
  }),
  createTemplate({
    id: 'tpl-almeirao',
    name: 'Almeirão',
    variant: 'Folha',
    category: 'Folhosa',
    cycleDays: 50,
    purchaseTypeDefault: 'bandeja',
    unitsPerPurchasePack: 288,
    productionUnitDefault: 'muda',
    salesUnitDefault: 'unidade',
    unitsPerSalesBox: 12,
    spacingBetweenPlantsCm: 30,
    spacingBetweenRowsCm: 20,
    bedLengthDefaultM: 50,
    bedWidthDefaultM: 1,
    plantsPerBed: null,
    weeklyProductionEstimate: null,
    bedsWithoutBreak: null,
    ...zeroCosts,
    notes: 'Aparece no planejamento macro de disponibilidade e fotoperíodo, sem detalhamento de custo.',
    sourceTags: [sourceTags.planning],
    recommendedMarkupPct: 38,
    defaultLossRate: 10,
    environmentType: 'canteiro',
    groupTag: 'folhosas',
    active: true
  }),
  createTemplate({
    id: 'tpl-coentro',
    name: 'Coentro',
    variant: 'Folha',
    category: 'Erva / tempero',
    cycleDays: 105,
    purchaseTypeDefault: 'bandeja',
    unitsPerPurchasePack: 288,
    productionUnitDefault: 'muda',
    salesUnitDefault: 'maco',
    unitsPerSalesBox: 20,
    spacingBetweenPlantsCm: 20,
    spacingBetweenRowsCm: 20,
    bedLengthDefaultM: 50,
    bedWidthDefaultM: 1,
    plantsPerBed: 1250,
    weeklyProductionEstimate: 0,
    bedsWithoutBreak: 0,
    ...zeroCosts,
    notes: 'Nova entrada listada no planejamento; sem base de custo no CSV de preços.',
    sourceTags: [sourceTags.beds, sourceTags.planning],
    recommendedMarkupPct: 40,
    defaultLossRate: 12,
    environmentType: 'canteiro',
    groupTag: 'temperos',
    active: true
  }),
  createTemplate({
    id: 'tpl-pepino-comum',
    name: 'Pepino',
    variant: 'Comum',
    category: 'Fruto',
    cycleDays: 90,
    purchaseTypeDefault: 'bandeja',
    unitsPerPurchasePack: 120,
    productionUnitDefault: 'muda',
    salesUnitDefault: 'caixa',
    unitsPerSalesBox: 12,
    spacingBetweenPlantsCm: 100,
    spacingBetweenRowsCm: 50,
    bedLengthDefaultM: 50,
    bedWidthDefaultM: 1.2,
    plantsPerBed: 120,
    weeklyProductionEstimate: 15,
    bedsWithoutBreak: 31,
    ...zeroCosts,
    notes: 'Planejamento indica cultivo em linha, tutorado.',
    sourceTags: [sourceTags.beds, sourceTags.planning],
    recommendedMarkupPct: 42,
    defaultLossRate: 15,
    environmentType: 'tutorado',
    groupTag: 'frutos',
    active: true
  }),
  createTemplate({
    id: 'tpl-abobrinha',
    name: 'Abobrinha',
    variant: 'Italiana',
    category: 'Fruto',
    cycleDays: 40,
    purchaseTypeDefault: 'bandeja',
    unitsPerPurchasePack: 120,
    productionUnitDefault: 'muda',
    salesUnitDefault: 'caixa',
    unitsPerSalesBox: 12,
    spacingBetweenPlantsCm: 100,
    spacingBetweenRowsCm: 50,
    bedLengthDefaultM: 50,
    bedWidthDefaultM: 1.2,
    plantsPerBed: 120,
    weeklyProductionEstimate: 30,
    bedsWithoutBreak: null,
    ...zeroCosts,
    notes: 'Nova entrada futura no planejamento, em cultivo tutorado.',
    sourceTags: [sourceTags.beds, sourceTags.planning],
    recommendedMarkupPct: 42,
    defaultLossRate: 15,
    environmentType: 'tutorado',
    groupTag: 'frutos',
    active: true
  })
];

export const activeCultureTemplates = cultureTemplates.filter((template) => template.active);

export const findCultureTemplateById = (templateId: string) => cultureTemplates.find((template) => template.id === templateId) ?? null;
