import type { BookRecord } from "@/lib/demo/types";

export const books: BookRecord[] = [
  { testament: "old", order: 1, osis: "Gen", slug: "genesis", name: "Gênesis", englishName: "Genesis", abbr: "Gn", aliases: ["genesis", "gênesis", "gn", "gen"], chapterCount: 50 },
  { testament: "old", order: 2, osis: "Exod", slug: "exodo", name: "Êxodo", englishName: "Exodus", abbr: "Êx", aliases: ["exodo", "êxodo", "ex", "êx", "exo", "exodus"], chapterCount: 40 },
  { testament: "old", order: 3, osis: "Lev", slug: "levitico", name: "Levítico", englishName: "Leviticus", abbr: "Lv", aliases: ["levitico", "levítico", "lv", "lev", "leviticus"], chapterCount: 27 },
  { testament: "old", order: 4, osis: "Num", slug: "numeros", name: "Números", englishName: "Numbers", abbr: "Nm", aliases: ["numeros", "números", "nm", "num", "numbers"], chapterCount: 36 },
  { testament: "old", order: 5, osis: "Deut", slug: "deuteronomio", name: "Deuteronômio", englishName: "Deuteronomy", abbr: "Dt", aliases: ["deuteronomio", "deuteronômio", "dt", "deut", "deuteronomy"], chapterCount: 34 },
  { testament: "old", order: 6, osis: "Josh", slug: "josue", name: "Josué", englishName: "Joshua", abbr: "Js", aliases: ["josue", "josué", "js", "joshua"], chapterCount: 24 },
  { testament: "old", order: 7, osis: "Judg", slug: "juizes", name: "Juízes", englishName: "Judges", abbr: "Jz", aliases: ["juizes", "juízes", "jz", "jdg", "judges"], chapterCount: 21 },
  { testament: "old", order: 8, osis: "Ruth", slug: "rute", name: "Rute", englishName: "Ruth", abbr: "Rt", aliases: ["rute", "rt", "ruth"], chapterCount: 4 },
  { testament: "old", order: 9, osis: "1Sam", slug: "1-samuel", name: "1 Samuel", englishName: "1 Samuel", abbr: "1Sm", aliases: ["1 samuel", "1samuel", "1sm", "i samuel", "1 sam", "1sam"], chapterCount: 31 },
  { testament: "old", order: 10, osis: "2Sam", slug: "2-samuel", name: "2 Samuel", englishName: "2 Samuel", abbr: "2Sm", aliases: ["2 samuel", "2samuel", "2sm", "ii samuel", "2 sam", "2sam"], chapterCount: 24 },
  { testament: "old", order: 11, osis: "1Kgs", slug: "1-reis", name: "1 Reis", englishName: "1 Kings", abbr: "1Rs", aliases: ["1 reis", "1reis", "1rs", "i reis", "1 kings", "1kgs"], chapterCount: 22 },
  { testament: "old", order: 12, osis: "2Kgs", slug: "2-reis", name: "2 Reis", englishName: "2 Kings", abbr: "2Rs", aliases: ["2 reis", "2reis", "2rs", "ii reis", "2 kings", "2kgs"], chapterCount: 25 },
  { testament: "old", order: 13, osis: "1Chr", slug: "1-cronicas", name: "1 Crônicas", englishName: "1 Chronicles", abbr: "1Cr", aliases: ["1 cronicas", "1 crônicas", "1cr", "1 chronicles", "1chr"], chapterCount: 29 },
  { testament: "old", order: 14, osis: "2Chr", slug: "2-cronicas", name: "2 Crônicas", englishName: "2 Chronicles", abbr: "2Cr", aliases: ["2 cronicas", "2 crônicas", "2cr", "2 chronicles", "2chr"], chapterCount: 36 },
  { testament: "old", order: 15, osis: "Ezra", slug: "esdras", name: "Esdras", englishName: "Ezra", abbr: "Ed", aliases: ["esdras", "ed", "ezra"], chapterCount: 10 },
  { testament: "old", order: 16, osis: "Neh", slug: "neemias", name: "Neemias", englishName: "Nehemiah", abbr: "Ne", aliases: ["neemias", "ne", "neh", "nehemiah"], chapterCount: 13 },
  { testament: "old", order: 17, osis: "Esth", slug: "ester", name: "Ester", englishName: "Esther", abbr: "Et", aliases: ["ester", "et", "esth", "esther"], chapterCount: 10 },
  { testament: "old", order: 18, osis: "Job", slug: "jo", name: "Jó", englishName: "Job", abbr: "Jó", aliases: ["jo", "jó", "job"], chapterCount: 42 },
  { testament: "old", order: 19, osis: "Ps", slug: "salmos", name: "Salmos", englishName: "Psalms", abbr: "Sl", aliases: ["salmos", "sl", "ps", "psalm", "psalms"], chapterCount: 150 },
  { testament: "old", order: 20, osis: "Prov", slug: "proverbios", name: "Provérbios", englishName: "Proverbs", abbr: "Pv", aliases: ["proverbios", "provérbios", "pv", "prov", "proverbs"], chapterCount: 31 },
  { testament: "old", order: 21, osis: "Eccl", slug: "eclesiastes", name: "Eclesiastes", englishName: "Ecclesiastes", abbr: "Ec", aliases: ["eclesiastes", "ec", "ecc", "ecclesiastes"], chapterCount: 12 },
  { testament: "old", order: 22, osis: "Song", slug: "canticos", name: "Cânticos", englishName: "Song of Songs", abbr: "Ct", aliases: ["canticos", "cânticos", "ct", "cantares", "song of songs", "song"], chapterCount: 8 },
  { testament: "old", order: 23, osis: "Isa", slug: "isaias", name: "Isaías", englishName: "Isaiah", abbr: "Is", aliases: ["isaias", "isaías", "is", "isa", "isaiah"], chapterCount: 66 },
  { testament: "old", order: 24, osis: "Jer", slug: "jeremias", name: "Jeremias", englishName: "Jeremiah", abbr: "Jr", aliases: ["jeremias", "jr", "jer", "jeremiah"], chapterCount: 52 },
  { testament: "old", order: 25, osis: "Lam", slug: "lamentacoes", name: "Lamentações", englishName: "Lamentations", abbr: "Lm", aliases: ["lamentacoes", "lamentações", "lm", "lam", "lamentations"], chapterCount: 5 },
  { testament: "old", order: 26, osis: "Ezek", slug: "ezequiel", name: "Ezequiel", englishName: "Ezekiel", abbr: "Ez", aliases: ["ezequiel", "ez", "ezk", "ezekiel"], chapterCount: 48 },
  { testament: "old", order: 27, osis: "Dan", slug: "daniel", name: "Daniel", englishName: "Daniel", abbr: "Dn", aliases: ["daniel", "dn", "dan"], chapterCount: 12 },
  { testament: "old", order: 28, osis: "Hos", slug: "oseias", name: "Oseias", englishName: "Hosea", abbr: "Os", aliases: ["oseias", "os", "hos", "hosea"], chapterCount: 14 },
  { testament: "old", order: 29, osis: "Joel", slug: "joel", name: "Joel", englishName: "Joel", abbr: "Jl", aliases: ["joel", "jl"], chapterCount: 3 },
  { testament: "old", order: 30, osis: "Amos", slug: "amos", name: "Amós", englishName: "Amos", abbr: "Am", aliases: ["amos", "amós", "am"], chapterCount: 9 },
  { testament: "old", order: 31, osis: "Obad", slug: "obadias", name: "Obadias", englishName: "Obadiah", abbr: "Ob", aliases: ["obadias", "ob", "obadiah"], chapterCount: 1 },
  { testament: "old", order: 32, osis: "Jonah", slug: "jonas", name: "Jonas", englishName: "Jonah", abbr: "Jn", aliases: ["jonas", "jn", "jonah"], chapterCount: 4 },
  { testament: "old", order: 33, osis: "Mic", slug: "miqueias", name: "Miqueias", englishName: "Micah", abbr: "Mq", aliases: ["miqueias", "mq", "mic", "micah"], chapterCount: 7 },
  { testament: "old", order: 34, osis: "Nah", slug: "naum", name: "Naum", englishName: "Nahum", abbr: "Na", aliases: ["naum", "na", "nah", "nahum"], chapterCount: 3 },
  { testament: "old", order: 35, osis: "Hab", slug: "habacuque", name: "Habacuque", englishName: "Habakkuk", abbr: "Hc", aliases: ["habacuque", "hc", "hab", "habakkuk"], chapterCount: 3 },
  { testament: "old", order: 36, osis: "Zeph", slug: "sofonias", name: "Sofonias", englishName: "Zephaniah", abbr: "Sf", aliases: ["sofonias", "sf", "zeph", "zephaniah"], chapterCount: 3 },
  { testament: "old", order: 37, osis: "Hag", slug: "ageu", name: "Ageu", englishName: "Haggai", abbr: "Ag", aliases: ["ageu", "ag", "hag", "haggai"], chapterCount: 2 },
  { testament: "old", order: 38, osis: "Zech", slug: "zacarias", name: "Zacarias", englishName: "Zechariah", abbr: "Zc", aliases: ["zacarias", "zc", "zech", "zechariah"], chapterCount: 14 },
  { testament: "old", order: 39, osis: "Mal", slug: "malaquias", name: "Malaquias", englishName: "Malachi", abbr: "Ml", aliases: ["malaquias", "ml", "mal", "malachi"], chapterCount: 4 },
  { testament: "new", order: 40, osis: "Matt", slug: "mateus", name: "Mateus", englishName: "Matthew", abbr: "Mt", aliases: ["mateus", "mt", "matthew", "matt"], chapterCount: 28 },
  { testament: "new", order: 41, osis: "Mark", slug: "marcos", name: "Marcos", englishName: "Mark", abbr: "Mc", aliases: ["marcos", "mc", "mark", "mrk"], chapterCount: 16 },
  { testament: "new", order: 42, osis: "Luke", slug: "lucas", name: "Lucas", englishName: "Luke", abbr: "Lc", aliases: ["lucas", "lc", "luke", "luk"], chapterCount: 24 },
  { testament: "new", order: 43, osis: "John", slug: "joao", name: "João", englishName: "John", abbr: "Jo", aliases: ["joao", "joão", "jo", "john", "jn"], chapterCount: 21 },
  { testament: "new", order: 44, osis: "Acts", slug: "atos", name: "Atos", englishName: "Acts", abbr: "At", aliases: ["atos", "at", "acts"], chapterCount: 28 },
  { testament: "new", order: 45, osis: "Rom", slug: "romanos", name: "Romanos", englishName: "Romans", abbr: "Rm", aliases: ["romanos", "rm", "rom", "romans"], chapterCount: 16 },
  { testament: "new", order: 46, osis: "1Cor", slug: "1-corintios", name: "1 Coríntios", englishName: "1 Corinthians", abbr: "1Co", aliases: ["1 corintios", "1 coríntios", "1co", "1 cor", "1corinthians"], chapterCount: 16 },
  { testament: "new", order: 47, osis: "2Cor", slug: "2-corintios", name: "2 Coríntios", englishName: "2 Corinthians", abbr: "2Co", aliases: ["2 corintios", "2 coríntios", "2co", "2 cor", "2corinthians"], chapterCount: 13 },
  { testament: "new", order: 48, osis: "Gal", slug: "galatas", name: "Gálatas", englishName: "Galatians", abbr: "Gl", aliases: ["galatas", "gálatas", "gl", "gal", "galatians"], chapterCount: 6 },
  { testament: "new", order: 49, osis: "Eph", slug: "efesios", name: "Efésios", englishName: "Ephesians", abbr: "Ef", aliases: ["efesios", "efésios", "ef", "eph", "ephesians"], chapterCount: 6 },
  { testament: "new", order: 50, osis: "Phil", slug: "filipenses", name: "Filipenses", englishName: "Philippians", abbr: "Fp", aliases: ["filipenses", "fp", "phil", "philippians"], chapterCount: 4 },
  { testament: "new", order: 51, osis: "Col", slug: "colossenses", name: "Colossenses", englishName: "Colossians", abbr: "Cl", aliases: ["colossenses", "cl", "col", "colossians"], chapterCount: 4 },
  { testament: "new", order: 52, osis: "1Thess", slug: "1-tessalonicenses", name: "1 Tessalonicenses", englishName: "1 Thessalonians", abbr: "1Ts", aliases: ["1 tessalonicenses", "1ts", "1 thessalonians", "1thess"], chapterCount: 5 },
  { testament: "new", order: 53, osis: "2Thess", slug: "2-tessalonicenses", name: "2 Tessalonicenses", englishName: "2 Thessalonians", abbr: "2Ts", aliases: ["2 tessalonicenses", "2ts", "2 thessalonians", "2thess"], chapterCount: 3 },
  { testament: "new", order: 54, osis: "1Tim", slug: "1-timoteo", name: "1 Timóteo", englishName: "1 Timothy", abbr: "1Tm", aliases: ["1 timoteo", "1 timóteo", "1tm", "1 timothy", "1tim"], chapterCount: 6 },
  { testament: "new", order: 55, osis: "2Tim", slug: "2-timoteo", name: "2 Timóteo", englishName: "2 Timothy", abbr: "2Tm", aliases: ["2 timoteo", "2 timóteo", "2tm", "2 timothy", "2tim"], chapterCount: 4 },
  { testament: "new", order: 56, osis: "Titus", slug: "tito", name: "Tito", englishName: "Titus", abbr: "Tt", aliases: ["tito", "tt", "titus"], chapterCount: 3 },
  { testament: "new", order: 57, osis: "Phlm", slug: "filemom", name: "Filemom", englishName: "Philemon", abbr: "Fm", aliases: ["filemom", "fm", "philemon", "phlm"], chapterCount: 1 },
  { testament: "new", order: 58, osis: "Heb", slug: "hebreus", name: "Hebreus", englishName: "Hebrews", abbr: "Hb", aliases: ["hebreus", "hb", "heb", "hebrews"], chapterCount: 13 },
  { testament: "new", order: 59, osis: "Jas", slug: "tiago", name: "Tiago", englishName: "James", abbr: "Tg", aliases: ["tiago", "tg", "james", "jas"], chapterCount: 5 },
  { testament: "new", order: 60, osis: "1Pet", slug: "1-pedro", name: "1 Pedro", englishName: "1 Peter", abbr: "1Pe", aliases: ["1 pedro", "1pe", "1 peter", "1pet"], chapterCount: 5 },
  { testament: "new", order: 61, osis: "2Pet", slug: "2-pedro", name: "2 Pedro", englishName: "2 Peter", abbr: "2Pe", aliases: ["2 pedro", "2pe", "2 peter", "2pet"], chapterCount: 3 },
  { testament: "new", order: 62, osis: "1John", slug: "1-joao", name: "1 João", englishName: "1 John", abbr: "1Jo", aliases: ["1 joao", "1 joão", "1jo", "1 john", "1jn"], chapterCount: 5 },
  { testament: "new", order: 63, osis: "2John", slug: "2-joao", name: "2 João", englishName: "2 John", abbr: "2Jo", aliases: ["2 joao", "2 joão", "2jo", "2 john", "2jn"], chapterCount: 1 },
  { testament: "new", order: 64, osis: "3John", slug: "3-joao", name: "3 João", englishName: "3 John", abbr: "3Jo", aliases: ["3 joao", "3 joão", "3jo", "3 john", "3jn"], chapterCount: 1 },
  { testament: "new", order: 65, osis: "Jude", slug: "judas", name: "Judas", englishName: "Jude", abbr: "Jd", aliases: ["judas", "jd", "jude"], chapterCount: 1 },
  { testament: "new", order: 66, osis: "Rev", slug: "apocalipse", name: "Apocalipse", englishName: "Revelation", abbr: "Ap", aliases: ["apocalipse", "ap", "revelation", "rev"], chapterCount: 22 }
];

export const booksByTestament = {
  old: books.filter((book) => book.testament === "old"),
  new: books.filter((book) => book.testament === "new")
};
